CREATE TABLE "GCG_5364_RW_FLEX"(
 "SCHEDULE" CHAR(6),
 "SCHEDULE_SUFFIX" CHAR(3),
 "JOB" CHAR(6),
 "SUFFIX" CHAR(3),
 "LABOR_SEQ" CHAR(6),
 "REWORK_QTY" DOUBLE);

CREATE INDEX "GCG_5364_RW_FLEX" ON "GCG_5364_RW_FLEX"("SCHEDULE", "SCHEDULE_SUFFIX", "JOB", "SUFFIX", "LABOR_SEQ");