CREATE TABLE "GCG_5364_FLEX_COMM" (
 "SCHEDULE" CHAR(6),
 "SCHEDULE_SUFFIX" CHAR(3),
 "COMMENT_1" LONGVARCHAR,
 "COMMENT_2" LONGVARCHAR,
 "COMMENT_3" LONGVARCHAR);

CREATE INDEX "GCG_5364_FLEX_COMM" USING 0 ON "GCG_5364_FLEX_COMM"("SCHEDULE","SCHEDULE_SUFFIX");
