Create Table "GCG_5364_PRESS_OPT"(
 "USER" CHAR(25) NOT NULL,
 "DATE_BATCHED" DATETIME NOT NULL,
 "FINISH" CHAR(50),
 "OPT_PERCENT" NUMERIC(12,4),
 "AREA_USED" NUMERIC(12,4),
 "AREA_AVAILABLE" NUMERIC(12,4),
 "SHEET_SIZE" CHAR(25),
 "WORKCENTER" CHAR(4) );