CREATE TABLE "GCG_5364_BATCH"(
 "BATCHED" BIT DEFAULT '0' NOT NULL,
 "JOB" CHAR(6) NOT NULL,
 "SUFFIX" CHAR(3),
 "SEQ" CHAR(6) NOT NULL );

CREATE INDEX "GCG_5364_BATCH" USING 0 ON "GCG_5364_BATCH"("JOB","SUFFIX","SEQ");