CREATE TABLE "GCG_5364_INVC_HIST" (
 "INVOICE" CHAR(7),
 "ORDER_NO" CHAR(7),
 "ORDER_LINE" CHAR(4),
 "ORDER_SUFFIX" CHAR(4),
 "DATE_INVOICE" DATE,
 "MATL" CHAR(20),
 "MATL_DESC" CHAR(30),
 "FINISH" CHAR(20),
 "FIN_DESC" CHAR(30),
 "LENGTH" DOUBLE,
 "WIDTH" DOUBLE,
 "DRILL_CODE" CHAR(20),
 "NOTES" VARCHAR(250),
 "BATCH_NOTES" CHAR(200) );

CREATE INDEX "GCG_5364_INVC_HIST" ON "GCG_5364_INVC_HIST"("ORDER_NO", "ORDER_LINE", "INVOICE", "ORDER_SUFFIX");