CREATE TABLE "GCG_5364_WIP_QUEUE"(
 "REC_NO" IDENTITY,
 "BIN" CHAR(6),
 "LOT" CHAR(15),
 "HEAT" CHAR(15),
 "SERIAL_NUMBER" CHAR(50),
 "JOB" CHAR(6),
 "SUFFIX" CHAR(3),
 "PART" CHAR(20),
 "QTY_SCANNED" INTEGER,
 "QTY_ORDER" INTEGER,
 "ORDER_NO" CHAR(7),
 "ORDER_LINE" CHAR(4));