CREATE TABLE "GCG_5364_UpCut"(
 "BIRUNID" BIGINT,
 "JOB" CHAR(6),
 "SUFFIX" CHAR(3),
 "SEQ" CHAR(6),
 "SCHED" CHAR(9),
 "MATL" CHAR(20),
 "WORKCENTER" CHAR(4),
 "CUT_QTY" DOUBLE,
 "CUT_ANGLE" CHAR(2),
 "CUT_LENGTH" DOUBLE,
 "CUT_WIDTH" DOUBLE );

CREATE INDEX "GCG_5364_UpCut" ON "GCG_5364_UpCut"("BIRUNID");

