CREATE TABLE "GCG_5364_NON_DOOR_WO"(
 "JOB" CHAR(6),
 "SUFFIX" CHAR(3),
 "PART" CHAR(20),
 "JOB_RELEASED" BIT DEFAULT '0' NOT NULL );

CREATE INDEX "GCG_5364_NON_DOOR_WO" USING 0 ON "GCG_5364_NON_DOOR_WO"("JOB", "SUFFIX");