CREATE TABLE "GCG_5364_MC_CONFIG" (
 "REC_NO" INTEGER,
 "MC_CODE" CHAR(30),
 "COL_HEAD" CHAR(30),
 "ANS_COL" BIT NOT NULL,
 "DATA_FIELD" CHAR(50),
 "FORMULA" LONGVARCHAR,
 "INS_FORMULA" LONGVARCHAR,
 "RAILS" LONGVARCHAR,
 "STILES" LONGVARCHAR,
 "LABEL_DATA" BIT NOT NULL,
 "FIVE_PIECE_DOOR" BIT NOT NULL,
 "RAILS_STILES" BIT NOT NULL );

CREATE INDEX "GCG_5364_MC_CONFIG" ON "GCG_5364_MC_CONFIG" ( "REC_NO", "MC_CODE" );
